#! /usr/bin/expect

#
# Copyright (c) 2025 Logan Ryan McLintock. All rights reserved.
#
# The contents of this file are subject to the
# Common Development and Distribution License (CDDL) version 1.1
# (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License in
# the LICENSE file included with this software or at
# https://opensource.org/license/cddl-1-1
#
# NOTICE PURSUANT TO SECTION 4.2 OF THE LICENSE:
# This software is prohibited from being distributed or otherwise made
# available under any subsequent version of the License.
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#

spawn ./test_input
expect "=> "
# Starts off quickly.
send "A\x1B\x5B\x32\x7En"
# n enters non-blocking, cooked mode.
expect "=> _"
send "\x1B\x5B\x32\x7E"
expect "=> 107"
expect "=> _"
send "\x1B\x5B\x36\x7E"
expect "=> 10A"
expect "=> _"
send "d"
# d enters non-blocking, double-cooked mode.
expect "=> 64"
expect "=> _"
send "\x01\x02\x03\x04\x05\x06"
expect "=> 200"
expect "=> _"
# Deliberately one less character.
send "\x01\x02\x03\x04\x05"
expect "=> 01"
expect "=> 02"
expect "=> 03"
expect "=> 04"
expect "=> 05"
expect "=> _"
send "\x1Bx"
expect "=> 201"
expect "=> _"
send "\x1B\x4F\x50\x1B\x4F\x51\x1B\x5B\x32\x34\x7E\x1B\x5B\x33\x7E"
    send "\x1B\x5B\x35\x7E"
expect "=> 202"
expect "=> _"
send "q"
expect "=> 71"
expect eof
